import type { Metadata } from "next";
import { LegalFooter, LegalHeader } from "../legal-shared";

export const metadata: Metadata = { title: "Datenschutz | RM Bauservice", description: "Datenschutzerklärung der Website von RM Bauservice – Rino Melis.", alternates: { canonical: "/datenschutz/" } };

export default function Datenschutz() { return <><LegalHeader /><main className="legal-page"><article className="container legal-content"><p className="eyebrow">Stand: September 2026</p><h1>Datenschutzerklärung</h1>
<h2>1. Verantwortlicher</h2><p>Verantwortlicher für die Verarbeitung personenbezogener Daten auf dieser Website ist:</p><p>RM Bauservice – Rino Melis<br />Inhaber: Rino Melis<br />Rudolf-Diesel-Straße 1<br />71106 Magstadt<br />Deutschland</p><p>Telefon: <a href="tel:+4917660849000">+49 176 60849000</a><br />E-Mail: <a href="mailto:rinomelis@web.de">rinomelis@web.de</a><br />Website: <a href="https://www.bauservice-rm.de">www.bauservice-rm.de</a></p>
<h2>2. Allgemeine Hinweise zur Datenverarbeitung</h2><p>Personenbezogene Daten sind alle Informationen, durch die eine natürliche Person unmittelbar oder mittelbar identifiziert werden kann. Wir verarbeiten personenbezogene Daten nur, soweit dies zur Bereitstellung dieser Website, zur Bearbeitung von Anfragen oder zur Durchführung vorvertraglicher beziehungsweise vertraglicher Maßnahmen erforderlich ist.</p><p>Die Verarbeitung erfolgt insbesondere auf Grundlage von Art. 6 Abs. 1 lit. b DSGVO bei Verträgen oder vorvertraglichen Anfragen, Art. 6 Abs. 1 lit. f DSGVO zur Wahrung berechtigter Interessen, Art. 6 Abs. 1 lit. c DSGVO bei gesetzlichen Pflichten und Art. 6 Abs. 1 lit. a DSGVO, sofern zuvor eine Einwilligung eingeholt wurde.</p>
<h2>3. Hosting und technische Bereitstellung</h2>
<p>Diese Website wird bei Netlify, Inc., 512 2nd Street, Suite 200, San Francisco, CA 94107, USA, gehostet. Die Bereitstellung erfolgt über ein von Jürgen Knappich für RM Bauservice verwaltetes Netlify-Konto.</p>
<p>Beim Aufruf können insbesondere IP-Adresse, Datum und Uhrzeit, aufgerufene Seite oder Datei, Datenmenge, Browser, Betriebssystem, Referrer-URL und HTTP-Statuscode in Server-Protokolldateien verarbeitet werden. Die Verarbeitung dient der technisch sicheren, stabilen und effizienten Bereitstellung der Website und erfolgt auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO.</p>
<p>Dabei können personenbezogene Daten, insbesondere IP-Adressen und technische Zugriffsdaten, in die USA übermittelt werden. Netlify ist nach dem EU-US Data Privacy Framework zertifiziert. Für davon erfasste Übermittlungen erfolgt die Übertragung auf Grundlage des Angemessenheitsbeschlusses der Europäischen Kommission gemäß Art. 45 DSGVO.</p>
<p>Netlifys Vertragsbedingungen beziehen ein Data Processing Agreement ein, das die Verarbeitung personenbezogener Daten im Auftrag regelt, soweit eine solche Verarbeitung stattfindet. Für Übermittlungen, die nicht unter das EU-US Data Privacy Framework fallen, sieht dieses EU-Standardvertragsklauseln vor.</p>
<p>Weitere Informationen: <a href="https://www.netlify.com/privacy/" target="_blank" rel="noopener noreferrer">Datenschutzerklärung von Netlify</a> und <a href="https://www.netlify.com/pdf/netlify-dpa.pdf" target="_blank" rel="noopener noreferrer">Data Processing Agreement von Netlify</a>.</p>
<p>Protokolldaten werden gelöscht, sobald sie für diese Zwecke nicht mehr erforderlich sind, sofern keine Aufbewahrungspflichten oder Sicherheitsgründe eine längere Speicherung erfordern.</p>
<h2>4. Verschlüsselte Übertragung</h2><p>Diese Website wird über HTTPS bereitgestellt. Dadurch werden Daten zwischen Ihrem Endgerät und der Website vor dem unbefugten Mitlesen durch Dritte geschützt.</p>
<h2>5. Kontaktaufnahme per Telefon oder E-Mail</h2><p>Bei einer Kontaktaufnahme verarbeiten wir die übermittelten Daten, etwa Name, Telefonnummer, E-Mail-Adresse, Inhalt und Zeitpunkt der Anfrage sowie Angaben zum geplanten Projekt. Vertragsbezogene Anfragen werden auf Grundlage von Art. 6 Abs. 1 lit. b DSGVO verarbeitet; allgemeine Anfragen auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO.</p><p>Die Daten werden gelöscht, wenn die Anfrage abschließend bearbeitet ist und keine gesetzlichen Aufbewahrungspflichten oder berechtigten Gründe entgegenstehen. Bitte übermitteln Sie besonders sensible Informationen nicht unverschlüsselt per E-Mail.</p>
<h2>6. Kontaktaufnahme über WhatsApp</h2><p>Auf der Website befindet sich lediglich ein externer Link zu WhatsApp; ein Plugin oder eingebetteter Dienst wird nicht eingesetzt. Eine Verbindung entsteht erst beim Anklicken. Anbieter im Europäischen Wirtschaftsraum ist WhatsApp Ireland Limited, Merrion Road, Dublin 4, D04 X2K5, Irland.</p><p>Beim Öffnen des Links können IP-Adresse, Geräteinformationen und der aufgerufene Link an WhatsApp übermittelt werden. Bei einer Nachricht verarbeiten wir insbesondere Telefonnummer, WhatsApp-Namen, gegebenenfalls Profilbild, Inhalt, Zeitpunkt und übermittelte Dateien. Es wird ein gewöhnliches WhatsApp-Konto und nicht WhatsApp Business verwendet. Alternativ können Sie uns telefonisch oder per E-Mail kontaktieren.</p><p>Die Verarbeitung erfolgt bei vertragsbezogenen Anfragen nach Art. 6 Abs. 1 lit. b DSGVO und sonst nach Art. 6 Abs. 1 lit. f DSGVO. WhatsApp verarbeitet Daten nach eigenen Angaben auch außerhalb des EWR. Weitere Informationen: <a href="https://www.whatsapp.com/legal/privacy-policy-eea" target="_blank" rel="noopener noreferrer">Datenschutzerklärung von WhatsApp</a>. Nachrichten werden gelöscht, wenn sie nicht mehr benötigt werden und keine Aufbewahrungspflichten entgegenstehen.</p>
<h2>7. Cookies und Analyseverfahren</h2><p>Derzeit werden keine eigenen Analyse-, Statistik- oder Marketingdienste und keine einwilligungspflichtigen Cookies oder vergleichbaren Technologien eingesetzt. Insbesondere ist Google Analytics nicht eingebunden. Nach dem gegenwärtigen technischen Stand ist daher kein Einwilligungsbanner erforderlich. Künftige einwilligungspflichtige Dienste werden erst nach ausdrücklicher Einwilligung aktiviert; diese Erklärung wird dann angepasst.</p>
<h2>8. Externe Links</h2><p>Beim bloßen Besuch werden über externe Links noch keine Daten an den jeweiligen Anbieter übertragen. Erst nach dem Anklicken verlassen Sie diese Website; dann gelten die Datenschutzbestimmungen des jeweiligen Anbieters.</p>
<h2>9. Speicherdauer</h2><p>Personenbezogene Daten werden nur so lange gespeichert, wie es für den jeweiligen Zweck erforderlich ist. Eine längere Speicherung erfolgt insbesondere bei gesetzlichen Aufbewahrungspflichten oder zur Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen.</p>
<h2>10. Empfänger personenbezogener Daten</h2><p>Empfänger können insbesondere Netlify als Hostinganbieter, der E-Mail-Anbieter, WhatsApp bei einer von Ihnen veranlassten Kommunikation sowie Steuerberater und Behörden sein, soweit dies zur Bereitstellung der Website, zur Anfragebearbeitung, zur Vertragsdurchführung oder aufgrund einer gesetzlichen Pflicht erforderlich ist.</p>
<h2>11. Ihre Rechte</h2><p>Sie haben im Rahmen der gesetzlichen Voraussetzungen insbesondere Rechte auf Auskunft (Art. 15 DSGVO), Berichtigung (Art. 16 DSGVO), Löschung (Art. 17 DSGVO), Einschränkung (Art. 18 DSGVO), Datenübertragbarkeit (Art. 20 DSGVO), Widerspruch (Art. 21 DSGVO) und Widerruf einer Einwilligung mit Wirkung für die Zukunft. Zur Ausübung können Sie die oben genannten Kontaktdaten verwenden. Bei Verarbeitungen nach Art. 6 Abs. 1 lit. f DSGVO können Sie aus Gründen Ihrer besonderen Situation jederzeit widersprechen.</p>
<h2>12. Beschwerderecht bei einer Aufsichtsbehörde</h2><p>Sie können sich bei einer Datenschutzaufsichtsbehörde beschweren. Zuständig ist: Der Landesbeauftragte für den Datenschutz und die Informationsfreiheit Baden-Württemberg, Heilbronner Straße 35, 70191 Stuttgart, Telefon 0711 615541-0, E-Mail <a href="mailto:poststelle@lfdi.bwl.de">poststelle@lfdi.bwl.de</a>, Website <a href="https://www.baden-wuerttemberg.datenschutz.de/" target="_blank" rel="noopener noreferrer">baden-wuerttemberg.datenschutz.de</a>.</p>
<h2>13. Keine automatisierte Entscheidungsfindung</h2><p>Eine automatisierte Entscheidungsfindung einschließlich Profiling im Sinne von Art. 22 DSGVO findet nicht statt.</p>
<h2>14. Aktualisierung dieser Datenschutzerklärung</h2><p>Wir behalten uns vor, diese Datenschutzerklärung anzupassen, wenn sich gesetzliche Vorgaben, die Website oder die eingesetzten Dienste ändern. Es gilt die jeweils veröffentlichte Fassung.</p>
</article></main><LegalFooter /></>; }
